spring.application.name=ms-autenticacao

#JWT Chave de Segurança
application.security.jwt.secret-key=SuaChaveSecretaMuitoLongaEseguraAquiParaAssinarTokensJWT12345!@#$%
application.security.jwt.expiration=86400000

# Configurações para desabilitar temporariamente a auto-configuração de banco de dados(ITEM JA REMOVIDO)
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#Confguracao do Banco de dados H2
spring.datasource.url=jdbc:h2:mem:testedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
